### ISSUE TITLE
[OpenShift4]Installing with cert-manager operator

### ISSUE THREAD

**Issue by hongkailiu** [jetstack/cert-manager-olm#13]
**Describe the bug**:
https://cert-manager.io/docs/installation/openshift/#installing-with-cert-manager-operator
Follow the above doc. 
Install the cert-manager via operator-hub on OCP 4.4.4

The pods are running:

```
oc --context build02 get pod -n cert-manager
NAME                                      READY   STATUS    RESTARTS   AGE
cert-manager-74474fc98f-b4v2x             1/1     Running   0          96m
cert-manager-cainjector-f55ccfc78-qf4kw   1/1     Running   0          96m
cert-manager-webhook-5f6c45d48c-59klm     1/1     Running   0          96m
```

```
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: cert-issuer
spec:
  acme:
    email: openshift-ci-robot@redhat.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cert-issuer-account-key
    solvers:
    - dns01:
        clouddns:
          project: openshift-ci-infra
          serviceAccountSecretRef:
            name: cert-issuer
            key: key.json
```

```
oc --context build02 apply -f clusters/build-clusters/02_cluster/cert-manager/cert-issuer_clusterissuer.yaml 
Error from server (InternalError): error when creating "clusters/build-clusters/02_cluster/cert-manager/cert-issuer_clusterissuer.yaml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=30s: dial tcp 10.131.0.188:10250: connect: connection refused
```

cert-manager-cainjector-f55ccfc78-qf4kw seems having permission issues

```
E0528 21:38:09.279943       1 leaderelection.go:320] error retrieving resource lock cert-manager/cert-manager-cainjector-leader-election-core: configmaps "cert-manager-cainjector-leader-election-core" is forbidden: User "system:serviceaccount:cert-manager:cert-manager-cainjector" cannot get resource "configmaps" in API group "" in the namespace "cert-manager"
```

**Expected behaviour**:
`CertIssuer` can be created successfully.

**Steps to reproduce the bug**:

- create namespace `cert-manager`.
- On Operator Hub UI, deploy it to the namespace.
- create the cluster-issuer above.

**Anything else we need to know?**:

The non-operator installation works well:

```hash
oc apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v0.15.1/cert-manager.yaml
```

**Environment details:**:
- Kubernetes version (e.g. v1.10.2):
```
oc version --context build02
Client Version: 4.5.0-202005290637-0087eb3
Server Version: 4.4.4
Kubernetes Version: v1.17.1
```
- Cloud-provider/provisioner (e.g. GKE, kops AWS, etc):
AWS
- cert-manager version (e.g. v0.4.0):
v0.15.1
- Install method (e.g. helm or static manifests):
Operator Hub UI

/kind bug
