### ISSUE TITLE
Add relatedImages to clusterserviceversion manifest

### ISSUE THREAD

**Issue by made-with-care** [jetstack/cert-manager-olm#18]
Please add relatedImages to clusterserviceversion, it useful for mirroring images to air-gaped environment via `oc adm catalog mirror <catalog> <dest_registry>`.

Example for `cert-manager-operator.v0.15.1.clusterserviceversion.yaml`:

```yaml
...
spec:
  relatedImages:
  - name: cert-manager-controller
    image: registry.connect.redhat.com/jetstack/cert-manager-controller:v0.15.1-ubi
  - name: cert-manager-acmesolver
    image: registry.connect.redhat.com/jetstack/cert-manager-acmesolver:v0.15.1-ubi
  - name: cert-manager-cainjector
    image: registry.connect.redhat.com/jetstack/cert-manager-cainjector:v0.15.1-ubi
  - name: cert-manager-webhook
    image: registry.connect.redhat.com/jetstack/cert-manager-webhook:v0.15.1-ubi
...
```
